//
// Created by Sherman Yan on 4/19/23.
//

#ifndef DIZZLESTUDIOPRO_PANELTYPEENUM_H
#define DIZZLESTUDIOPRO_PANELTYPEENUM_H


enum PanelTypeEnum{
    KEYBOARD,
    DRUMPAD,
    AUDIO,
    VOCAL,
    EMPTY_PANEL

};
#endif //DIZZLESTUDIOPRO_PANELTYPEENUM_H
