//
// Created by Sherman Yan on 12/6/22.
//

enum TextureEnums{
    PAUSE_BUTTON,
    PLAY_BUTTON,
    PLAY_BUTTON_GREY,
    PAUSE_BUTTON_RED,
    MIC_BUTTON_RED,
    KEYBOARD_LABEL,
    DRUMPAD_LABEL,
    AUDIO_LABEL,
    VOCAL_LABEL,
    EMPTY_LABEL,
    DROP_DOWN_MENU,
    TRACKCONTROLS_FORWARD,
    TRACKCONTROLS_LOOP,
    TRACKCONTROLS_PAUSE,
    TRACKCONTROLS_PLAY,
    TRACKCONTROLS_REWIND,
    TRACKCONTROLS_FORWARD_LIGHT,
    TRACKCONTROLS_LOOP_LIGHT,
    TRACKCONTROLS_REWIND_LIGHT,
    AUDIOBARS,
    LAST_TEX
};