//
// Created by Sherman Yan on 12/6/22.
//

enum TextureEnums{
    PAUSE_BUTTON,
    PLAY_BUTTON,
    PLAY_BUTTON_GREY,
    PAUSE_BUTTON_RED,
    MIC_BUTTON_RED,
    KEYBOARD_LABEL,
    DRUMPAD_LABEL,
    AUDIO_LABEL,
    VOCAL_LABEL,
    EMPTY_LABEL,
    DROP_DOWN_MENU,
    LAST_TEX
};