//
// Created by Sherman Yan on 4/14/23.
//

#ifndef DIZZLESTUDIOPRO_DRAWABLEAUDIONODE_H
#define DIZZLESTUDIOPRO_DRAWABLEAUDIONODE_H


class DrawableAudioNode {

};


#endif //DIZZLESTUDIOPRO_DRAWABLEAUDIONODE_H
